import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<div className={"bg-background"}>*/}
        <div className={"bg-background"}>
          {children}
        </div>

        <script type="application/javascript" dangerouslySetInnerHTML={{ __html: `
			function loadScript() {
			  var head = document.getElementsByTagName('head')[0];
			  var script = document.createElement('script');
			  script.type = 'text/javascript';
			  script.src = "https://test-resources.vercel.app/embedai.js";
			  script.setAttribute('data-id', "embedai-Qclufpg5");
			  script.id = "embedai";
			  head.appendChild(script);
			}
			if (!location.href.includes("ai-demo-my-chatbot")) {
			  loadScript();
			}
		  `}}>
        </script>
      </body>
    </html>
  )
}
